### ISSUE TITLE
hex pacage?

### ISSUE THREAD

**Issue by Licenser** [ferd/merklet#3]
Hey any chance to get a hex package of this? :) I can prepare and publish it too hand it over when you want to take it over, but figured I ask first.

**Comment by ferd** [comment]
Oh yeah that would be fine. If you want to send a PR for this stuff that will make my life simpler. Still catching up post-vacation.

**Comment by Licenser** [comment]
sure will do :) hope the vacation was great :D

**Comment by ferd** [comment]
Done and done! THanks for the help.
